language: python
dist: xenial # required for Python >= 3.7
python:
  - 3.5
  - 3.6
  - 3.7
before_install:
  - sudo apt-get install -y ffmpeg
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
script:
  - pytest --cov
after_success:
  - pip install codecov
  - codecov
